# -*- coding: utf-8 -*-
"""Titanic_classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ws7taCezq9G0SgqYoD6srMYP8plRJOww

# **TITANIC CLASSIFICATION**
"""

import pandas as pd
train=pd.read_csv('/content/train.csv')
test=pd.read_csv('/content/test (1).csv')
train[:4]

train.isnull().sum()

test.isnull().sum()

impute_value = train['Age'].median()
train['Age'] = train['Age'].fillna(impute_value)
test['Age'] = test['Age'].fillna(impute_value)

train['IsFemale']=(train['Sex'] == 'female').astype(int)
test['IsFemale']=(test['Sex'] == 'female').astype(int)

predictors=['Pclass','IsFemale','Age']
x_train=train[predictors].values
x_test=test[predictors].values
y_train=train['Survived'].values
x_train[:5]

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(x_train,y_train)

y_predict = model.predict(x_test)
y_predict[:10]

from sklearn.model_selection import cross_val_score
model=LogisticRegression(C=10)
scores=cross_val_score(model,x_train,y_train,cv=4)
scores